//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserListApplication.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    public partial class User
    {
        public int userID { get; set; }

        /*
         This must be passed in. Cannot be null.
         Gets and sets first name
         */
        [Required]
        [Display(Name = "First Name")]
        public string firstName { get; set; }

        /*
         This must be passed in. Cannot be null.
         Gets and sets last name
             */
        [Required]
        [Display(Name = "Last Name")]
        public string lastName { get; set; }

        [Display(Name = "Name")]
        public string name
        {
            get
            {
                return this.firstName + " " + this.lastName;
            }
        }

        [Required]
        [Remote("doesUserNameExist", "Users", ErrorMessage = "Username already in use. Please enter a different user name.")]
        [Display(Name = "Username")]
        public string userName { get; set; }

        [Required]
        [Remote("doesEmailExist", "Users", ErrorMessage = "Email already in use. ")]
        [EmailAddress]
        [Display(Name = "E-mail")]
        public string email { get; set; }

        [Display(Name = "Joined")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime joined { get; set; }
    }
}
